### ISSUE TITLE
Splitting modules (Some chunks are larger than 500 kBs after minification)

### ISSUE THREAD

**Issue by sberprime** [pixelate-it/pixelbattle-frontend#32]
This error
```diff
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
```
cannot interfere with the site, but mobile players die from long compilation, together with @mirdukkkkk we conducted a small investigation

# Why does this happen?
If we divide the frontend into modules (libraries), we will get the following result after minification: ![idea64](https://github.com/pixelate-it/pixelbattle-frontend/assets/150621959/b031c151-fdf4-4419-8ec1-4122dec317f7)

WE FOUND THE IMPOSTER! Oh yeah, `@pixi` lib is what all the fuss is about, suggest what we can do below.

# Test results
## Lighthouse (Navigation - Mobile)
![LIghthouse](https://github.com/pixelate-it/pixelbattle-frontend/assets/150621959/7054a7a8-6fef-4d36-8e52-87bc5d2363b8)
## LIghthouse (Navigation - Desktop)
![LIghthouse](https://github.com/pixelate-it/pixelbattle-frontend/assets/150621959/e54debe3-4b65-46fb-a2b4-fff2229e74a9)

# My comments
![LIghthouse](https://github.com/pixelate-it/pixelbattle-frontend/assets/150621959/976c7631-8c6a-4ffc-8edf-5f3dfc7bc700)
The Lighthouse itself says that `@pixi` is stuffed with too much unusual shit, I’m waiting for the developer’s response on this matter

Thx @mirdukkkkk and me.

**Comment by sberprime** [comment]
![image](https://github.com/pixelate-it/pixelbattle-frontend/assets/150621959/a6108846-dca4-474c-8560-9636cb983d73)
Lighthouse info

**Comment by mirdukkkkk** [comment]
currently in dev branch (without division by libraries)
# Lighthouse (Navigation - Mobile)
![mobile](https://cdn.pixelbattle.fun/file/2024/01/chrome_jCvH54ulMn.png)
# Lighthouse (Navigation - Desktop)
![desktop](https://cdn.pixelbattle.fun/file/2024/01/chrome_CC8i7JUoWR.png)

2 times faster ⚡

**Comment by sberprime** [comment]
fine
